name: module3_task1

on:
  push:
    paths:
      - 'module3_task1/**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Execute the script setup.sh
        run: |
          cd module3_task1/
          ./setup.sh
      - name: Build the application
        run: |
          cd module3_task1/
          make build
