name: module3_task1
on:
  schedule:
    - cron: "0 0 * * *"
  push:
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3
      - name: Run setup.sh
        working-directory: module3_task1
        run: sudo ./setup.sh
      - name: Build the site
        working-directory: module3_task1
        run: make build
      - name: Create a post
        working-directory: module3_task1
        run: make post POST_NAME=test POST_TITLE=thisisatest
      - name: Call for help :3
        working-directory: module3_task1
        run: make help
      - name: Clean the dist folder
        working-directory: module3_task1
        run: make clean
