---
name: module3_task1
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  module3_task0:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: lint
        run: |
          cd module3_task1/
          make lint
      - name: setup
        run: |
          cd module3_task1/
          sudo ./setup.sh
      - name: build
        run: |
          cd module3_task1/
          make build
      - name: tests
        run: |
          cd module3_task1/
          make POST_TITLE="test" POST_NAME="test" post
      - name: test
        run: |
          cd module3_task1/
          make test
      - name: clean
        run: |
          cd module3_task1/
          make clean
