name: module3_task3

on:
  push:
    branches: [master]
    tags:
      - "*.*.*"
  schedule:
    - cron: '30 00 * * *'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Run bash script"
        run: |
          cd module3_task3 && ./setup.sh
      - name: "Run make build"
        run: |
          cd module3_task3 && make build
      - name: "Run make target package"
        run: |
          cd module3_task3 && make package
      - name: "Run make target lint"
        run: |
          cd module3_task3 && make lint
      - name: "Uni-Test"
        run: |
          cd module3_task3 && make unit-tests
      - name: "Integration-tests" 
        run: |
          cd module3_task3 && make integration-tests
      - name: "validate" 
        run: |
          cd module3_task3 && make validate
      - name: "Archive production artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: file named awesome-website
          path: |
            module3_task3/awesome-website.zip
      - name: "Release task 3"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: module3_task3/DEPLOY.md
          files: |
            module3_task3/DEPLOY.md
            module3_task3/awesome-website.zip
